baseURL: https://romas05.github.io/resume-hugo/
languageCode: en-us
build:
  writeStats: true
params:
  title: myCV
  author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Сорокин Роман Сергеевич"
    tagline: Студент
    location: "г. Йошкар-Ола"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "#"
        title: GitHub
      - icon: fab fa-telegram
        url: "#"
        title: Telegram 
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
  aboutme:
    title: Обо мне
    icon: fas fa-user
    description: Студент 4-го курса ПС
  experience: 
    title: Опыт работы
    icon: fas fa-briefcase
    list:
      - position: Пока что нет  
  education:
    title: Образование
    icon: fas fa-graduation-cap
    list:
      - degree: СОШ №9  
  project:
    title: Мои работы
    icon: fas fa-project-diagram
    list:
      - title: Проект 1
        url: "#"
        description: Описание проекта
      - title: Проект 2
        url: "#"
        description: Описание проекта
      - title: Проект 3
        url: "#"
        description: Описание проекта
      - title: Проект 4
        url: "#"
        description: Описание проекта
